# LiveKit DigitalOcean Configuration
# Based on: https://raw.githubusercontent.com/livekit/livekit-helm/refs/heads/master/examples/server-do.yaml

replicaCount: 2

# Graceful termination for active sessions
terminationGracePeriodSeconds: 18000

livekit:
  # Enable Prometheus metrics
  prometheus_port: 6789
  log_level: info
  
  rtc:
    use_external_ip: true
    # Port range for WebRTC traffic
    port_range_start: 50000
    port_range_end: 60000
    tcp_port: 7881
  
  redis:
    address: "redis-service:6379"
  
  # API keys (will be overridden by secrets)
  keys:
    myapikey: "myapisecret"
  
  turn:
    enabled: true
    # Your domain for TURN server
    domain: "livekit.bnkd.me"
    # TURN/TLS port over TCP
    tls_port: 3478
    # TURN/UDP port
    udp_port: 3478
    # Kubernetes Secret containing TLS cert
    secretName: "livekit-turn-tls"
    # Use LoadBalancer for TURN service
    serviceType: "LoadBalancer"

# DigitalOcean load balancer configuration
loadBalancer:
  type: do
  # TLS certificate generated automatically with cert-manager / letsencrypt
  clusterIssuer: letsencrypt-prod
  tls:
    - hosts:
        - livekit.bnkd.me
      secretName: livekit-tls

# Enable autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

# Resources for 8-core instance
resources:
  limits:
    cpu: 7500m
    memory: 2048Mi
  requests:
    cpu: 7000m
    memory: 1024Mi
