# Local Development Patches
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090

---
apiVersion: v1
kind: Service
metadata:
  name: voice-agent-service
spec:
  type: NodePort
  selector:
    app: voice-agent
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
    nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: livekit-server
spec:
  type: NodePort
  selector:
    app: livekit-server
  ports:
  - name: http
    port: 80
    targetPort: 7880
    nodePort: 30080
  - name: rtc-tcp
    port: 7881
    targetPort: 7881
    nodePort: 30781